words:
  - biome
  - biomejs
  - clsx
  - cmdk
  - embla
  - hookform
  - lucide
  - lucide-react
  - hono
  - neondatabase
  - openapi
  - solistack
  - sonner
  - tanstack
  - turbopack
  - ultracite
  - vaul