import type { Metadata, Viewport } from "next"
import { ThemeProvider } from "next-themes"

import { cn } from "@soli/ui/cn"
import "@soli/ui/css"
import { Toaster } from "@soli/ui/toaster"

import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" }
  ]
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className={cn(GeistSans.variable, GeistMono.variable)}>
          {children}
        </body>
        <Toaster />
      </ThemeProvider>
    </html>
  )
}
