name: Deploy Production

on:
  push:
    branches:
      - "main"

env:
  # TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  # TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  # VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  spell-lint:
    name: Spellcheck Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Checks
        run: bun turbo lint:spell

  web:
    name: Web CI
    runs-on: ubuntu-latest

    env:
      # Database URL
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Auth Secret
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

      # Github OAuth
      AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
      AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Checks
        run: bun turbo lint

      - name: Install Vercel CLI
        run: bun install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
